[server]
enableCORS = false
enableXsrfProtection = false
headless = true
port = 8501
address = "0.0.0.0"

[browser]
gatherUsageStats = false
serverAddress = "localhost"
serverPort = 8501

[theme]
base = "dark"
primaryColor = "#3CA2F6"
backgroundColor = "#0a0a0f"
secondaryBackgroundColor = "#16161d"
textColor = "#ffffff"
font = "sans serif"
